name: PlatformIO CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install dependencies
      run: | 
        pio pkg install -e all-deps --no-save
        pio pkg update --no-save
    - name: Copy secrets
      run: cp include/secrets.example.h include/secrets.h
    - name: Build chieftain
      run: pio run -e chieftain
    - name: Build demo
      run: pio run -e demo
    - name: Build heltecdemo
      run: pio run -e heltecdemo
    # Uncomment the following two lines once platformio.ini includes a lantern env definition
    # - name: Build lantern
    #   run: pio run -e lantern
    - name: Build ledstrip
      run: pio run -e ledstrip
    - name: Build ledstrip_feather
      run: pio run -e ledstrip_feather
    - name: Build m5plusdemo
      run: pio run -e m5plusdemo
    - name: Build mesmerizer
      run: pio run -e mesmerizer
    - name: Build panlee
      run: pio run -e panlee
    - name: Build spectrum
      run: pio run -e spectrum
    - name: Build umbrella
      run: pio run -e umbrella
    - name: Build xmastrees
      run: pio run -e xmastrees
